# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "minimal/jessie64"

  # More powerful VM
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    #!/bin/bash

    # See docker install procedure
    apt-get purge "lxc-docker*"
    apt-get purge "docker.io*"
    apt-get update

    # Configure repository
    apt-get install -y apt-transport-https ca-certificates
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    echo "deb https://apt.dockerproject.org/repo debian-jessie main" >/etc/apt/sources.list.d/docker.list

    # Update with new sources
    apt-get update

    # Install programs
    apt-get install -y docker-engine git curl wget tmux socat

    # Enable docker for non-root
    gpasswd -a vagrant docker

    echo "set -g default-terminal screen-256color" >~vagrant/.tmux.conf

    # Enable and start services
    systemctl daemon-reload
    systemctl enable docker
    systemctl start docker
  SHELL

  config.vm.synced_folder "../", "/home/vagrant/docker-swarm-compose", owner: 'vagrant', group: 'vagrant'
  config.vm.network "private_network", ip: "10.1.1.10"
end
